# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: driver.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'driver.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x64river.proto\"`\n\rDriverRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0bphoneNumber\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x1d\n\x06status\x18\x04 \x01(\x0e\x32\r.WorkerStatus\"@\n\x13\x44riverUpdateRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x1d\n\x06status\x18\x02 \x01(\x0e\x32\r.WorkerStatus\"j\n\x0b\x44riverReply\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0bphoneNumber\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t\x12\x1d\n\x06status\x18\x05 \x01(\x0e\x32\r.WorkerStatus\"\x1d\n\x0f\x44riverIdRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\x07\n\x05\x45mpty\"0\n\x0f\x44riverListReply\x12\x1d\n\x07\x64rivers\x18\x01 \x03(\x0b\x32\x0c.DriverReply*5\n\x0cWorkerStatus\x12\x0b\n\x07\x44riving\x10\x00\x12\x0b\n\x07Resting\x10\x01\x12\x0b\n\x07OffDuty\x10\x02\x32\xc1\x01\n\x0b\x44riverProto\x12)\n\tAddDriver\x12\x0e.DriverRequest\x1a\x0c.DriverReply\x12+\n\tGetDriver\x12\x10.DriverIdRequest\x1a\x0c.DriverReply\x12&\n\nGetDrivers\x12\x06.Empty\x1a\x10.DriverListReply\x12\x32\n\x0cUpdateDriver\x12\x14.DriverUpdateRequest\x1a\x0c.DriverReplyB\x14\xaa\x02\x11TrackAndTraceGrpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'driver_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\021TrackAndTraceGrpc'
  _globals['_WORKERSTATUS']._serialized_start=378
  _globals['_WORKERSTATUS']._serialized_end=431
  _globals['_DRIVERREQUEST']._serialized_start=16
  _globals['_DRIVERREQUEST']._serialized_end=112
  _globals['_DRIVERUPDATEREQUEST']._serialized_start=114
  _globals['_DRIVERUPDATEREQUEST']._serialized_end=178
  _globals['_DRIVERREPLY']._serialized_start=180
  _globals['_DRIVERREPLY']._serialized_end=286
  _globals['_DRIVERIDREQUEST']._serialized_start=288
  _globals['_DRIVERIDREQUEST']._serialized_end=317
  _globals['_EMPTY']._serialized_start=319
  _globals['_EMPTY']._serialized_end=326
  _globals['_DRIVERLISTREPLY']._serialized_start=328
  _globals['_DRIVERLISTREPLY']._serialized_end=376
  _globals['_DRIVERPROTO']._serialized_start=434
  _globals['_DRIVERPROTO']._serialized_end=627
# @@protoc_insertion_point(module_scope)
