# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import driver_pb2 as driver__pb2

GRPC_GENERATED_VERSION = '1.69.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in driver_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DriverProtoStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddDriver = channel.unary_unary(
                '/DriverProto/AddDriver',
                request_serializer=driver__pb2.DriverRequest.SerializeToString,
                response_deserializer=driver__pb2.DriverReply.FromString,
                _registered_method=True)
        self.GetDriver = channel.unary_unary(
                '/DriverProto/GetDriver',
                request_serializer=driver__pb2.DriverIdRequest.SerializeToString,
                response_deserializer=driver__pb2.DriverReply.FromString,
                _registered_method=True)
        self.GetDrivers = channel.unary_unary(
                '/DriverProto/GetDrivers',
                request_serializer=driver__pb2.Empty.SerializeToString,
                response_deserializer=driver__pb2.DriverListReply.FromString,
                _registered_method=True)
        self.UpdateDriver = channel.unary_unary(
                '/DriverProto/UpdateDriver',
                request_serializer=driver__pb2.DriverUpdateRequest.SerializeToString,
                response_deserializer=driver__pb2.DriverReply.FromString,
                _registered_method=True)


class DriverProtoServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddDriver(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDriver(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDrivers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateDriver(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DriverProtoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddDriver': grpc.unary_unary_rpc_method_handler(
                    servicer.AddDriver,
                    request_deserializer=driver__pb2.DriverRequest.FromString,
                    response_serializer=driver__pb2.DriverReply.SerializeToString,
            ),
            'GetDriver': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDriver,
                    request_deserializer=driver__pb2.DriverIdRequest.FromString,
                    response_serializer=driver__pb2.DriverReply.SerializeToString,
            ),
            'GetDrivers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDrivers,
                    request_deserializer=driver__pb2.Empty.FromString,
                    response_serializer=driver__pb2.DriverListReply.SerializeToString,
            ),
            'UpdateDriver': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateDriver,
                    request_deserializer=driver__pb2.DriverUpdateRequest.FromString,
                    response_serializer=driver__pb2.DriverReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DriverProto', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('DriverProto', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DriverProto(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddDriver(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DriverProto/AddDriver',
            driver__pb2.DriverRequest.SerializeToString,
            driver__pb2.DriverReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDriver(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DriverProto/GetDriver',
            driver__pb2.DriverIdRequest.SerializeToString,
            driver__pb2.DriverReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDrivers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DriverProto/GetDrivers',
            driver__pb2.Empty.SerializeToString,
            driver__pb2.DriverListReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateDriver(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DriverProto/UpdateDriver',
            driver__pb2.DriverUpdateRequest.SerializeToString,
            driver__pb2.DriverReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
