# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import package_pb2 as package__pb2

GRPC_GENERATED_VERSION = '1.69.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in package_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PackageProtoStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddPackage = channel.unary_unary(
                '/PackageProto/AddPackage',
                request_serializer=package__pb2.PackageRequest.SerializeToString,
                response_deserializer=package__pb2.PackageReply.FromString,
                _registered_method=True)
        self.UpdatePackage = channel.unary_unary(
                '/PackageProto/UpdatePackage',
                request_serializer=package__pb2.UpdatePackageRequest.SerializeToString,
                response_deserializer=package__pb2.PackageReply.FromString,
                _registered_method=True)


class PackageProtoServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddPackage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePackage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PackageProtoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddPackage': grpc.unary_unary_rpc_method_handler(
                    servicer.AddPackage,
                    request_deserializer=package__pb2.PackageRequest.FromString,
                    response_serializer=package__pb2.PackageReply.SerializeToString,
            ),
            'UpdatePackage': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePackage,
                    request_deserializer=package__pb2.UpdatePackageRequest.FromString,
                    response_serializer=package__pb2.PackageReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PackageProto', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('PackageProto', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PackageProto(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddPackage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PackageProto/AddPackage',
            package__pb2.PackageRequest.SerializeToString,
            package__pb2.PackageReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePackage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PackageProto/UpdatePackage',
            package__pb2.UpdatePackageRequest.SerializeToString,
            package__pb2.PackageReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
