# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: timer.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'timer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btimer.proto\"\x1e\n\x0eSetTimeRequest\x12\x0c\n\x04time\x18\x01 \x01(\t\"\"\n\x0fSetTimeResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x12\n\x10ResetTimeRequest\"$\n\x11ResetTimeResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x14\n\x12\x43urrentTimeRequest\"B\n\x13\x43urrentTimeResponse\x12\x14\n\x0c\x63urrent_time\x18\x01 \x01(\t\x12\x15\n\rprevious_time\x18\x02 \x01(\t2\xac\x01\n\x0bTimeService\x12,\n\x07SetTime\x12\x0f.SetTimeRequest\x1a\x10.SetTimeResponse\x12\x32\n\tResetTime\x12\x11.ResetTimeRequest\x1a\x12.ResetTimeResponse\x12;\n\x0eGetCurrentTime\x12\x13.CurrentTimeRequest\x1a\x14.CurrentTimeResponseB\x1d\xaa\x02\x1aTrackAndTrace.TimeProviderb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'timer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\032TrackAndTrace.TimeProvider'
  _globals['_SETTIMEREQUEST']._serialized_start=15
  _globals['_SETTIMEREQUEST']._serialized_end=45
  _globals['_SETTIMERESPONSE']._serialized_start=47
  _globals['_SETTIMERESPONSE']._serialized_end=81
  _globals['_RESETTIMEREQUEST']._serialized_start=83
  _globals['_RESETTIMEREQUEST']._serialized_end=101
  _globals['_RESETTIMERESPONSE']._serialized_start=103
  _globals['_RESETTIMERESPONSE']._serialized_end=139
  _globals['_CURRENTTIMEREQUEST']._serialized_start=141
  _globals['_CURRENTTIMEREQUEST']._serialized_end=161
  _globals['_CURRENTTIMERESPONSE']._serialized_start=163
  _globals['_CURRENTTIMERESPONSE']._serialized_end=229
  _globals['_TIMESERVICE']._serialized_start=232
  _globals['_TIMESERVICE']._serialized_end=404
# @@protoc_insertion_point(module_scope)
